package com.pos.backend.domain;

import jakarta.persistence.*;
import lombok.*;

/**
 * Person Entity - Represents a person in the POS system
 * 
 * This is a JPA Entity, which means:
 * - It maps to a database table called "persons"
 * - Each instance represents one row in that table
 * - JPA/Hibernate automatically handles saving/loading from database
 * 
 * LOMBOK ANNOTATIONS EXPLAINED:
 * @Data - Generates:
 *   - getters for all fields
 *   - setters for all non-final fields
 *   - toString() method
 *   - equals() and hashCode() methods
 *   This replaces ~100 lines of boilerplate code!
 * 
 * @NoArgsConstructor - Creates empty constructor: new Person()
 * @AllArgsConstructor - Creates constructor with all fields: new Person(name, address, ...)
 * 
 * @Entity - Tells JPA this class is a database entity
 * @Table - Specifies the database table name
 * 
 * @author Your Name
 * @version 2.0 (Modernized with JPA)
 */
@Entity                           // JPA: This is a database entity
@Table(name = "persons")         // JPA: Maps to "persons" table
@Data                            // Lombok: Auto-generates getters, setters, toString, equals, hashCode
@NoArgsConstructor               // Lombok: Creates empty constructor
@AllArgsConstructor              // Lombok: Creates constructor with all parameters
public class Person {

    /**
     * Primary Key (ID)
     * 
     * @Id - Marks this as the primary key
     * @GeneratedValue - Database auto-generates this value
     * IDENTITY strategy - Uses database auto-increment (1, 2, 3, ...)
     * 
     * Why Long not int? Long can hold bigger numbers and is nullable
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Person's full name
     * 
     * @Column annotations define database column properties:
     * - name: column name in database
     * - nullable: can this be NULL? (false = required field)
     * - length: maximum string length
     */
    @Column(name = "first_name", nullable = false, length = 50)
    private String firstName;

    @Column(name = "last_name", nullable = false, length = 50)
    private String lastName;

    /**
     * Person's address details
     * nullable = true means these are optional fields
     */
    @Column(name = "address", length = 200)
    private String address;

    @Column(name = "city", length = 50)
    private String city;

    @Column(name = "state", length = 2)  // State codes are 2 characters (CA, NY, etc.)
    private String state;

    @Column(name = "zip", length = 10)   // ZIP code: "12345" or "12345-6789"
    private String zip;

    @Column(name = "phone", length = 20)
    private String phone;

    /**
     * Social Security Number
     * 
     * IMPORTANT SECURITY NOTE:
     * - SSN is sensitive PII (Personally Identifiable Information)
     * - In production, this should be ENCRYPTED in database
     * - unique = true ensures no duplicate SSNs
     * - For this learning project, we're keeping it simple
     */
    @Column(name = "ssn", unique = true, length = 11)  // Format: "123-45-6789"
    private String ssn;

    /**
     * Relationship to Cashier
     * 
     * @OneToOne - One Person has one Cashier relationship
     * @JoinColumn - Creates foreign key column "cashier_id" in persons table
     * 
     * OPTIONAL RELATIONSHIP:
     * - Not all Persons are Cashiers
     * - optional = true means cashier can be null
     * - We'll uncomment this after creating Cashier entity
     */
    // Uncomment after creating Cashier entity:
    // @OneToOne
    // @JoinColumn(name = "cashier_id")
    // private Cashier cashier;

    /**
     * Custom constructor for convenience (without ID - ID is auto-generated)
     * 
     * This is useful when creating new Person objects before saving to database.
     * The database will assign the ID when you save.
     */
    public Person(String firstName, String lastName, String address, 
                  String city, String state, String zip, String phone, String ssn) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.phone = phone;
        this.ssn = ssn;
    }

    /**
     * Get full name (convenience method)
     * 
     * This is a "computed" field - not stored in database,
     * but calculated on-the-fly when you need it.
     */
    public String getFullName() {
        return firstName + " " + lastName;
    }

    /**
     * toString() is auto-generated by @Data, but we can customize it
     * 
     * SECURITY NOTE: Be careful logging SSN!
     * In production, mask it: "***-**-6789"
     */
    @Override
    public String toString() {
        return String.format("Person[id=%d, name=%s %s, city=%s, state=%s]",
                id, firstName, lastName, city, state);
    }
}
