package com.pos.backend.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for Person entity.
 * 
 * DTOs (Data Transfer Objects) are simplified versions of your entities
 * that control exactly what data is sent to/from the API.
 * 
 * WHY USE DTOs?
 * 1. SECURITY: Don't expose sensitive fields (like SSN) in API responses
 * 2. FLEXIBILITY: API shape can differ from database shape
 * 3. VALIDATION: Separate validation rules for create vs update
 * 4. DECOUPLING: Changes to entities don't break the API contract
 */
public class PersonDTO {

    /**
     * Request DTO - What the client sends when creating/updating a person.
     * Does NOT include 'id' (auto-generated by database).
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class Request {
        private String firstName;
        private String lastName;
        private String address;
        private String city;
        private String state;
        private String zip;
        private String phone;
        private String ssn;
    }

    /**
     * Response DTO - What the API returns to the client.
     * Includes 'id' but masks sensitive data like SSN.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class Response {
        private Long id;
        private String firstName;
        private String lastName;
        private String address;
        private String city;
        private String state;
        private String zip;
        private String phone;
        private String maskedSsn;  // Only last 4 digits shown: "***-**-6789"
    }
}
