package com.pos.backend.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for Person entity.
 * 
 * DTOs (Data Transfer Objects) are simplified versions of your entities
 * that control exactly what data is sent to/from the API.
 * 
 * WHY USE DTOs?
 * 1. SECURITY: Don't expose sensitive fields (like SSN) in API responses
 * 2. FLEXIBILITY: API shape can differ from database shape
 * 3. VALIDATION: Separate validation rules for create vs update
 * 4. DECOUPLING: Changes to entities don't break the API contract
 */
public class PersonDTO {

    /**
     * Request DTO - What the client sends when creating/updating a person.
     * Does NOT include 'id' (auto-generated by database).
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class Request {
        @NotBlank(message = "First name is required")
        @Size(max = 50, message = "First name must be at most 50 characters")
        private String firstName;

        @NotBlank(message = "Last name is required")
        @Size(max = 50, message = "Last name must be at most 50 characters")
        private String lastName;

        @Size(max = 200, message = "Address must be at most 200 characters")
        private String address;

        @Size(max = 50, message = "City must be at most 50 characters")
        private String city;

        @Size(min = 2, max = 2, message = "State must be exactly 2 characters")
        private String state;

        @Size(max = 10, message = "ZIP code must be at most 10 characters")
        private String zip;

        @Size(max = 20, message = "Phone must be at most 20 characters")
        private String phone;

        @Pattern(regexp = "^\\d{3}-\\d{2}-\\d{4}$", message = "SSN must be in format XXX-XX-XXXX")
        private String ssn;
    }

    /**
     * Response DTO - What the API returns to the client.
     * Includes 'id' but masks sensitive data like SSN.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class Response {
        private Long id;
        private String firstName;
        private String lastName;
        private String address;
        private String city;
        private String state;
        private String zip;
        private String phone;
        private String maskedSsn;  // Only last 4 digits shown: "***-**-6789"
    }
}
